# Generated by Django 6.0.5 on 2026-05-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservicerequest',
            old_name='vehicle_image',
            new_name='images',
        ),
    ]
