# Generated by Django 6.0.5 on 2026-05-11 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0002_rename_vehicle_image_userservicerequest_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workerview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=20)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='std_img/')),
                ('issue', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_worker', models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
