# Generated by Django 6.0.5 on 2026-05-11 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0003_workerview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userservicerequest',
            old_name='images',
            new_name='vehicle_image',
        ),
        migrations.AddField(
            model_name='userservicerequest',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='Description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='issue',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='vehicle',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Workerview',
        ),
    ]
