# Generated by Django 6.0.5 on 2026-05-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0004_master_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservicerequest',
            old_name='vehicle_image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='Description',
            field=models.CharField(help_text='if other , briefly decribe what you feels ', max_length=200),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='customer_name',
            field=models.CharField(help_text='Enter your Name ', max_length=100),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='issue',
            field=models.CharField(choices=[('Tyre-Puncher', 'Puncher'), ('Starting Issues', 'starting issues'), ('Other', 'other')], help_text='select your issue', max_length=20),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='location',
            field=models.CharField(help_text='enter your location ', max_length=20),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='vehicle',
            field=models.CharField(choices=[('2-Wheeler', '2-wheeler'), ('4-Wheeler.', '4-Wheeler'), ('4-Wheel above', 'above')], help_text='select Vehicle type ', max_length=20),
        ),
    ]
