# Generated by Django 6.0.5 on 2026-05-11 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0005_rename_vehicle_image_userservicerequest_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfuelrequest',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
