# Generated by Django 6.0.5 on 2026-05-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0006_userfuelrequest_assigned_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfuelrequest',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userfuelrequest',
            name='fuel_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userfuelrequest',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userfuelrequest',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='Description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='issue',
            field=models.CharField(choices=[('Tyre-Puncher', 'Puncher'), ('Starting Issues', 'starting issues'), ('Other', 'other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='vehicle',
            field=models.CharField(choices=[('2-Wheeler', '2-wheeler'), ('4-Wheeler.', '4-Wheeler'), ('4-Wheel above', 'above')], max_length=20),
        ),
    ]
