# Generated by Django 6.0.5 on 2026-05-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0009_alter_userfuelrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservicerequest',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
